version: '2.1'

networks:
  softwarefactory-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  alertmanager:
    image: prom/alertmanager 
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  nodeexporter:
    image: prom/node-exporter 
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
   ports:
      - "8080:8080"
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  pushgateway:
    image: prom/pushgateway 
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - =${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-aec4Fgh51f}
    restart: unless-stopped
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
