version: '3.3'

networks:
  softwarefactory-net:
    driver: bridge

volumes:
    sonarqube_db_data: {}
    sonarqube_front_data: {}

services:

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SONARQUBE_JDBC_USERNAME:-sonar}
      POSTGRES_USER: ${SONARQUBE_JDBC_PASSWORD:-dfrg87cv}
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  sonarqube_front:
    image: sonarqube
    container_name: sonarqube_front
    restart: unless-stopped
    ports:
      - ${SONARQUBE_PORT:-9000}:9000
      - ${SONARQUBE_PORT2:-9092}:9092
    volumes:
      - sonarqube_front_data:/opt/sonarqube/data
    depends_on:
       - sonarqube_db
    environment:
      SONARQUBE_JDBC_USERNAME: ${SONARQUBE_JDBC_USERNAME:-sonar}
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_JDBC_PASSWORD:-dfrg87cv}
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube_db/sonar?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
