version: '2.1'

networks:
  softwarefactory-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}
    jenkins_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "prometheus"

  alertmanager:
    image: prom/alertmanager 
    container_name: alertmanager
    hostname: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "alertmanager"

  nodeexporter:
    image: prom/node-exporter 
    container_name: nodeexporter
    hostname: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "nodeexporter"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "cadvisor"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-aec4Fgh51f}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "grafana"

  pushgateway:
    image: prom/pushgateway 
    container_name: pushgateway
    hostname: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "pushgateway"

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    hostname: caddy
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
      - "${PROMETHEUS_PORT:-9090}:9090"
      - "${ALERTMANAGER_PORT:-9093}:9093"
      - "${PUSHGATEWAY_PORT:-9091}:9091"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-aec4Fgh51f}
    restart: unless-stopped
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "caddy"

  jenkins:
    image: jenkins
    container_name: jenkins
    hostname: jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - no_proxy=127.0.0.1,localhost,sonarqube_front,gitlab
    restart: unless-stopped
    networks:
      - softwarefactory-net
    labels:
      org.label-schema.group: "softwarefactory"
      log_type: "jenkins"
