{
 "title": "[Docker] Bench",
 "tags": [
  "Prometheus",
  "pushgateway"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   {
    "name": "registry",
    "label": "Registry",
    "query": "label_values(docker_registry_vulnerability,instance)"
   },
   {
    "name": "repositories",
    "label": "Repositories_Images",
    "query": "label_values(docker_registry_vulnerability{instance=\"$registry\"},repositories)"
   },
   {
    "name": "tags",
    "label": "tags",
    "query": "label_values(docker_registry_vulnerability{repositories=\"$repositories\"},tags)"
   },
   {
    "name": "severity",
    "label": "severity",
    "query": "label_values(docker_registry_vulnerability,severity)"
   }
  ]
 },
 "panels": [
  {
   "title": "Images and container",
   "type": "graph",
   "description": "It is recommended to be at the lowest",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_image{instance=~\"$registry\",type=\"dangling\"}",
     "legendFormat": "image dangling"
    },
    {
     "expr": "docker_image{instance=~\"$registry\",type=\"other_registry\"}",
     "legendFormat": "[$registry] from_other/unknown_registry"
    },
    {
     "expr": "docker_image{instance=~\"$registry\",type=\"runcontainer\"}",
     "legendFormat": "[$registry] container wilth old image version tags"
    },
    {
     "expr": "docker_container{type!=\"up\"}",
     "legendFormat": "container {{type}}"
    },
    {
     "expr": "count(dockerbenchsecurity{job=\"dockerbench\"}) by (instance,version)",
     "legendFormat": "[Bench {{ version }}] {{ instance }}"
    }
   ]
  },
  {
   "title": "Image rebuild priority (more than 10 fix)",
   "type": "table",
   "description": "He must not have fields",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "docker_registry_fixedVersion{instance=~\"$registry\",repositories=~\"$repositories\",tags=~\"$tags\"} > 10"
    }
   ]
  },
  {
   "title": "Deployed images where tag are rebuild",
   "type": "table",
   "description": "He must not have fields",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "docker_container_to_run{instance=~\"$registry\",repository=~\"_$repositories\",tag=~\"$tags\"}"
    }
   ]
  },
  {
   "title": "Container log size (more than 250 MiB)",
   "type": "table",
   "description": "He must not have fields",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "docker_container_purge{instance=\"log\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Fixed version",
   "type": "graph",
   "description": "All values must be 0",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_registry_fixedVersion{instance=~\"$registry\",repositories=~\"$repositories\",tags=~\"$tags\"}",
     "legendFormat": "{{repositories}}:{{tags}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "graph",
   "description": "It is recommended to be at the lowest",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_registry_vulnerability{instance=\"harbor\",repositories=~\"$repositories\",tags=~\"$tags\",severity=~\"$severity\"}",
     "legendFormat": "[{{severity}}] {{repositories}}:{{tags}}"
    }
   ]
  }
 ]
}